package no.nav.familie.pdf.config

const val DOKUMENTTYPE_OVERGANGSSTØNAD = "OVERGANGSSTØNAD_SØKNAD"
const val DOKUMENTTYPE_OVERGANGSSTØNAD_VEDLEGG = "OVERGANGSSTØNAD_SØKNAD_VEDLEGG"

const val DOKUMENTTYPE_BARNETILSYN = "BARNETILSYNSTØNAD_SØKNAD"
const val DOKUMENTTYPE_BARNETILSYN_VEDLEGG = "BARNETILSYNSTØNAD_VEDLEGG"

const val DOKUMENTTYPE_SKJEMA_ARBEIDSSØKER = "SKJEMA_ARBEIDSSØKER"

const val DOKUMENTTYPE_SKOLEPENGER = "SKOLEPENGER_SØKNAD"
const val DOKUMENTTYPE_SKOLEPENGER_VEDLEGG = "SKOLEPENGER_VEDLEGG"

const val DOKUMENTTYPE_ETTERSENDING = "ETTERSENDING"
