apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-pdf
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 1Gi
      cpu: 100m
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-pdf.intern.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7"  # teamfamilie
  tokenx:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-mottak
          namespace: teamfamilie
          cluster: prod-gcp
        - application: k9-brukerdialog-prosessering
          namespace: dusseldorf
          cluster: prod-gcp
        - application: familie-baks-mottak
          namespace: teamfamilie
          cluster: prod-gcp
    outbound:
      rules:
        - application: familie-ef-mottak
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie
  leaderElection: true

