apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-pdf
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: { { image } }
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 512Mi
      cpu: 20m
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-pdf.intern.dev.nav.no
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-mottak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: k9-brukerdialog-prosessering
          namespace: dusseldorf
          cluster: dev-gcp
        - application: familie-baks-mottak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: skjemautfylling
          namespace: skjemadigitalisering
          cluster: dev-gcp
        - application: skjemautfylling-delingslenke
          namespace: skjemadigitalisering
          cluster: dev-gcp
        - application: skjemautfylling-preprod
          namespace: skjemadigitalisering
          cluster: dev-gcp
        - application: skjemautfylling-preprod-alt
          namespace: skjemadigitalisering
          cluster: dev-gcp
    outbound:
      external:
        - host: teamfamilie-unleash-api.nav.cloud.nais.io

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie
  leaderElection: true
