application:
  name: "familie-ef-mottak"
server:
  servlet:
    context-path: /

spring:
  data:
    jdbc:
      repositories:
        enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: srvfamilie-ef-mot
      max-poll-records: 1
      auto-offset-reset: latest
      enable-auto-commit: false
    producer:
      acks: all
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  flyway:
    enabled: true
    baseline-version: 6
    placeholders:
      ignoreIfLocal:
    ignore-migration-patterns: "*:missing"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ef-mottak
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-test-query: "select 1"
      max-lifetime: 900000
      minimum-idle: 1
logging:
  config: "classpath:logback-spring.xml"

springdoc:
  packagesToScan: no.nav.familie.pdf
  pathsToMatch: /v3/api-docs,/api/**
  swagger-ui:
    disable-swagger-default-url: true

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      health: "status/isAlive"
  prometheus.metrics.export.enabled: true
  health:
    db:
      enabled: true

unleash:
  enabled: true

familie:
  dokument:
    url: http://familie-dokument
    audience: prod-gcp:teamfamilie:familie-dokument
  ef:
    integrasjoner:
      url: https://familie-integrasjoner.prod-fss-pub.nais.io/api
    pdfgenerator:
      url: http://familie-brev

prosessering:
  enabled: true
  cronRetryTasks: "0 5 6,7 1/1 * ?"
  fixedDelayString:
    in:
      milliseconds: 10000
  delete:
    after:
      weeks: 4

database:
  encryption:
    # 16, 24 or 32 bytes
    key: ${DATABASEKEY}

JOURNALFOERINGHENDELSE_V1_TOPIC_URL: teamdokumenthandtering.aapen-dok-journalfoering
EF_SAK_URL: http://familie-ef-sak

KAFKA_TOPIC_DITTNAV: min-side.aapen-brukernotifikasjon-beskjed-v1
#STS_URL: http://security-token-service.default.svc.nais.local
ettersending.ettersendingUrl: https://www.nav.no/familie/alene-med-barn/ettersending

DB_RYDDING_CRON_EXPRESSION: 0 0 2 * * MON-FRI
