application:
  name: "familie-pdf"
server:
  servlet:
    context-path: /
  port: 9060

spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
logging:
  config: "classpath:logback-spring.xml"

springdoc:
  packagesToScan: no.nav.familie.pdf
  pathsToMatch: /v3/api-docs,/api/**
  swagger-ui:
    disable-swagger-default-url: true

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      health: "status/isAlive"
  prometheus.metrics.export.enabled: true
  health:
    db:
      enabled: true
