spring:
  flyway:
    enabled: true
    placeholders:
      ignoreIfProd:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ef-mottak
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-test-query: "select 1"
      max-lifetime: 900000
      minimum-idle: 1

familie:
  dokument:
    url: http://familie-dokument
    audience: dev-gcp:teamfamilie:familie-dokument
  ef:
    pdfgenerator:
      url: http://familie-brev
    integrasjoner:
      url: https://familie-integrasjoner.dev-fss-pub.nais.io/api
      scope: api://dev-fss.teamfamilie.familie-integrasjoner/.default

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
  client:
    registration:
      integrasjoner-client-credentials:
        resource-url: ${familie.ef.integrasjoner.url}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${familie.ef.integrasjoner.scope}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      ef-sak:
        resource-url: ${EF_SAK_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://dev-gcp.teamfamilie.familie-ef-sak/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      dokument:
        resource-url: ${familie.dokument.url}
        well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        token-exchange:
          audience: ${familie.dokument.audience}
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-auth-method: private_key_jwt
          client-jwk: ${TOKEN_X_PRIVATE_JWK}

JOURNALFOERINGHENDELSE_V1_TOPIC_URL: teamdokumenthandtering.aapen-dok-journalfoering

ettersending.ettersendingUrl: https://familie.ekstern.dev.nav.no/familie/alene-med-barn/ettersending

DB_RYDDING_CRON_EXPRESSION: 0 0 * * * ?

prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS